updated logs

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -21,10 +21,10 @@ jobs:
         run: |
           python logs.py
 
-    - name: Save logs
-      run: |
-        git config user.name "GitHub Action"
-        git config user.email "action@github.com"
-        git add logs.txt
-        git commit -m "Update logs" || echo "No changes"
-        git push || echo "Push failed"
+      - name: Save logs
+        run: |
+          git config user.name "GitHub Action"
+          git config user.email "action@github.com"
+          git add logs.txt
+          git commit -m "Update logs" || echo "No changes"
+          git push || echo "Push failed"
